import {test,expect} from "@playwright/test"
test("dropdown",async({page})=>{
    await page.goto("https://demoapps.qspiders.com/ui/dropdown?sublist=0")
    // await page.locator("#country_code").selectOption("+91")
    const code=page.locator("#country_code")
    await code.selectOption({index:0})
    // await expect(code).toHaveValue("+91")
    const selectedCode = await code.inputValue()
    expect(selectedCode).toBe("+91")
    await page.locator("#phone").type("1234567809")
    const radio=await page.locator("#male")
    await radio.check()
    await expect(radio).toBeChecked()
    await page.locator("#select3").selectOption({value:"India"})
    await page.locator("#select5").selectOption({value:"Rajasthan"})
    await page.locator('(//select[@class="border-0 px-3 py-3 placeholder-blueGray-300 text-blueGray-600 bg-white rounded text-sm shadow focus:outline-none focus:ring w-full ease-linear transition-all duration-150"])[3]').selectOption({value:"Jaipur"})
    await page.locator("#continuebtn").click()
})